# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'

    # Locale par défaut
    default_locale: en

    # Configuration du traducteur
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en

    # Session configuration
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    # Cache et routing
    router:
        utf8: true
        strict_requirements: null
