# config/packages/knp_paginator.yaml
knp_paginator:
  page_range: 5                        # Nombre de pages à afficher
  default_options:
    page_name: page                   # Nom du paramètre de pagination
    sort_field_name: sort             # Nom du paramètre de tri
    sort_direction_name: direction    # Nom du paramètre de direction de tri
    filter_field_name: filterField    # Nom du paramètre de filtre
    filter_value_name: filterValue    # Nom du paramètre de valeur de filtre
    distinct: true                    # Est-ce qu'on doit faire un "DISTINCT" sur les résultats
  template:
    pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' # Utilisation de Bootstrap 5
    sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
